schema_version = "1.0.0"

id = "instance_harvestor"
version = "0.0.3"
name = "Instance Harvestor"
tagline = "Relink Duplicated Meshes"
maintainer = "BlockyBard"
type = "add-on"

blender_version_min = "2.90.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
